== Instructions

=== prerequisits

Installation of:

* Wheezy
* ROS_comm (http://wiki.ros.org/indigo/Installation/Debian)
* Machinekit

see also link:https://github.com/machinekit/machinekit/issues/689#issuecomment-164146410[this comment]

=== Usage

in a 1st terminal run
```
halrun -I ~/ros_catkin_ws/src/ros_hello_machinekit/halfile.hal
```
in a 2nd terminal run which can be used for viewing the publisher and subscriber making HAL pins
```
watch -n 0.2 "halcmd show pin"
```

in a 3nd terminal run
```
roscore
```

in a 4nd terminal run
```
rosrun ros_hello_machinekit hello_world_publisher.py
```

in a 5rd terminal run
```
rosrun ros_hello_machinekit hello_world_subscriber.py
```

return to the first terminal
```
show comp
show pin
```

you'll notice the subscriber has the value of `0`. Thaty's because the pin `rospub-inside-HAL.value-in` is still `0`

type:
```
net cosine siggen.0.cosine rospub-inside-HAL.value-in
```

- observe in terminal 4 that the publisher now gets the values of the `siggen.0.cosine` pin from `siggen`
- observe in terminal 5 that the subscriber gets the value from the publisher
 
in a 6th terminal run
```
rosrun ros_hello_machinekit machinekit_subscriber.py
```

- observe in the 2nd terminal that the component and pin used for receiving data are made
- observe that the data from the publisher is put in the `rossub-outside-HAL.value-out` value.
